{
    "name": "Commandline Test",
    "id": "f00dbaad-dead-beef-baadf00d",
    "session": {
        "sleep_time": 0,
        "skip": 0
    },
    "target": {
        "transport": {
            "media": "commandline"
        },
        "target": {
            "command": "/Users/zsoltimre/Desktop/Devel/FuzzLabs/engine-new/engine/test",
            "parameters": [
                "<<payload>>"
            ]
        }
    },
    "conditions": {
        "fail_connection": ["pass"],
        "fail_receive": ["pass"],
        "fail_send": ["pass"]
    },
    "scenarios": [
        {
            "name": "commandline scenario",
            "units": ["unit1"]
        }
    ]
}

