{
    "name": "Test Job 2",
    "id": "f00dbaad-dead-beef-baadf00d",
    "session": {
        "sleep_time": 0,
        "skip": 0
    },
    "target": {
        "transport": {
            "media": "stdout"
        }
    },
    "conditions": {
        "fail_connection": ["handle"],
        "fail_receive": ["pass"],
        "fail_send": ["handle"]
    },
    "scenarios": [
        {
            "name": "test scenario",
            "units": ["unit1", "unit2"]
        }
    ]
}

